### ISSUE TITLE
CogniCrypt failed to analyse a maven project

### ISSUE THREAD

**Issue by linghuiluo** [eclipse-cognicrypt/CogniCrypt#281]
**Describe the bug**
CogniCrypt failed to analyse a maven project

**To Reproduce**
Import the project as maven project in eclipse, click CogniCrypt button to analyse the project

**Expected behavior**
A set of misuses detected

**Screenshots**
The Error Log
![error1](https://user-images.githubusercontent.com/18470909/56819011-2db13400-6849-11e9-81e4-dd8fc71b46b5.PNG)
![error2](https://user-images.githubusercontent.com/18470909/56819012-2db13400-6849-11e9-975d-8241dd60766d.PNG)

**Desktop (please complete the following information):**
 - OS: windows

**The maven project**
[vault.zip](https://github.com/eclipse-cognicrypt/CogniCrypt/files/3121941/vault.zip)

**Comment by kruegers** [comment]
assigned @seena-mathew

**Comment by nguyenLisa** [comment]
I had a problem with the same symptoms (see below, "Static analysis failed for $projectName"). Forcing Eclipse to use Java 8 fixed it (modified the eclipse.ini file to change the Java version).

<img width="609" alt="Capture d’écran 2019-05-08 à 10 30 39" src="https://user-images.githubusercontent.com/1546847/57361708-4e4c8880-717d-11e9-951d-5f3e19ba79ee.png">

**Comment by johspaeth** [comment]
Thanks @nguyenLisa for reporting. @sritejakv has implemented a version check that notifies the user when Eclipse is running with a Java version higher than 8 (until the analysis also executes when Eclipse is running on a newer JVM #202).

**Comment by linghuiluo** [comment]
as you can see the session data in the last screenshot, i was using Java 8.

**Comment by johspaeth** [comment]
@seena-mathew the issue should be resolved when you use the current state of the `develop` branch. Could you please check?

**Comment by seena-mathew** [comment]
@johspaeth I tried with the current state of develop branch and it still throws the same error.

**Comment by seena-mathew** [comment]
@linghuiluo The Cognicrypt analysis for the project Vault is successful when tested with develop branch.
Please download the plugin from the below URL:
https://download.eclipse.org/cognicrypt/snapshot/?d
